move items in a playlist
aome510/spotify-player pull request #224
Opened 2023-07-26 17:21 UTC by cobbinma

add track actions to move items up and down in the current playlist 🎵

<img width="459" alt="Screenshot 2023-07-26 at 18 18 30" src="https://github.com/aome510/spotify-player/assets/578718/a61a24e4-8947-441c-8a5b-3fba934d399d">

closes #197

2023-07-28 02:11 UTC, aome510 commented
Hi @cobbinma, thanks for the PR. I think the original issue wants to implement the feature as commands instead of actions. I can find it quite troublesome, let's say, to move an item up 5 times as you need to call `GetAction`, wait for the popup then select the action. With command, you can just press a key.

It shouldn't be too difficult to change to command.

2023-07-28 13:47 UTC, cobbinma commented
> Hi @cobbinma, thanks for the PR. I think the original issue wants to implement the feature as commands instead of actions. I can find it quite troublesome, let's say, to move an item up 5 times as you need to call `GetAction...` command, wait for the popup then select the action. With command, you can just press a key.
> 
> It shouldn't be too difficult to change to command.

Thanks @aome510 

I agree, that is much easier 👍

2023-07-29 01:02 UTC, aome510 commented on spotify_player/src/event/window.rs
> +                                == data.user_data.user.as_ref().map(|user| &user.id)
This owner check can be moved inside the `find` function right.

2023-07-29 01:16 UTC, aome510 requested changes
Looking good. Only need a minor change

2023-07-29 01:34 UTC, aome510 commented
I just tried the feature but the ordering does not persist after restart it changes ordering in the UI, which I think mainly because we also update the cached. @cobbinma does it work for you?

2023-07-29 15:21 UTC, cobbinma commented
> I just tried the feature but the ordering change does not persist after restart. It does change the ordering in the UI though, which I think mainly because we also update the cached. @cobbinma does it work for you?

@aome510 It's only persisting moving upwards... 😕

2023-07-29 16:48 UTC, aome510 commented
> It's only persisting moving upwards... 😕

Oh right, also only persists moving upwards for me. Very interesting. Do you think you can investigate this behaviour? Otherwise, I think the PR is in a good state already.

2023-07-30 10:14 UTC, cobbinma commented
> > It's only persisting moving upwards... 😕
> 
> Oh right, also only persists moving upwards for me. Very interesting. Do you think you can investigate this behaviour? Otherwise, I think the PR is in a good state already.

@aome510

I misunderstood the difference between insert before and index when using update playlist items.

Should be fixed now 👍

2023-07-30 13:36 UTC, merged

2023-07-30 13:36 UTC, aome510 commented
Thanks @cobbinma