Add audio normalization device config option
aome510/spotify-player pull request #255
Opened 2023-09-17 04:38 UTC by jsbmg

This adds a device configuration option to set whether the audio is [normalized](https://en.wikipedia.org/wiki/Audio_normalization) or not. Turning it off can significantly improve sound quality and detail. 

By default, normalization is on (Spotify's default), but this allows to set it to false.

2023-09-17 17:54 UTC, aome510 commented on spotify_player/src/streaming.rs
> +	    .unwrap_or_default(),
the field itself is `bool` already. This part is redundant.

```suggestion
	    .normalization,
```

2023-09-17 17:54 UTC, aome510 requested changes
Thanks for the PR. Can you update https://github.com/aome510/spotify-player/blob/master/examples/app.toml as well?

2023-09-18 00:13 UTC, jsbmg commented
Thanks for the feedback. Just updated with those two changes.

2023-09-18 14:05 UTC, aome510 approved these changes

2023-09-20 14:25 UTC, aome510 commented
@jsbmg can you fix the CI failure?

2023-09-22 22:36 UTC, merged

2023-09-23 19:59 UTC, jsbmg commented
> @jsbmg can you fix the CI failure?

Hey, sorry, had a busy week, but thanks for fixing that and merging it. Appreciate your work.